### ISSUE TITLE
The server was attacked by a robot when it happens, so online gamers are being kicked out of the server. This is too silent.

### ISSUE THREAD

**Issue by shiqutong** [Kr1S-D/UltimateAntibot#1]
The server was attacked by a robot when it happens, so online gamers are being kicked out of the server. This is too silent.

**Comment by Kr1S-D** [comment]
Server type?

**Comment by shiqutong** [comment]
waterfall  paper1.16.5

**Comment by shiqutong** [comment]
I put this plug-in in the waterfall of BC side, the server is paper1.16.5, after the operation, in the event of attack, all normal players collective break line, the server.

**Comment by Kr1S-D** [comment]
the plugin has a temporary list where it puts all the players that enter, when there is a bot attack those in this list are disconnected

**Comment by shiqutong** [comment]
What I want is not your explanation of the cause of the problem, but a solution, so that online players will not be kicked out when the server is attacked. Please send me the correct configuration file for reference. thank you.

**Comment by Kr1S-D** [comment]
You just need to install the new version released today and set disconnect in the slowmode check to false
