### ISSUE TITLE
Please help me fix this. 

### ISSUE THREAD

**Issue by Aadi-mone** [Kr1S-D/UltimateAntibot#2]
![brb](https://user-images.githubusercontent.com/87631878/132539149-8c83bb63-9225-4a9d-8531-88deacbf1c2e.PNG)

This keeps spamming to users and Players can't enter the server, even if there is no bot attack.

**Comment by Kr1S-D** [comment]
are u using lastest version?
can u send me all uab files?

**Comment by Aadi-mone** [comment]
> are u using latest version?
YES
> can u send me all uab files?

The config's trigger is been changed to 15 bots in 1 seconds 
other than that I didn't change anything.

**Comment by Kr1S-D** [comment]
How did it all happen? have you been attacked?
Send me the uab files anyway

**Comment by Aadi-mone** [comment]
Nope, I am not getting attacked, and I can't upload .yml files in Github, because it doesn't suppot that type of file.
I may paste everything.

**##Config**

`version: 2.8
#   _    _ _ _   _                 _                        _   _ _           _
#  | |  | | | | (_)               | |           /\         | | (_) |         | |
#  | |  | | | |_ _ _ __ ___   __ _| |_ ___     /  \   _ __ | |_ _| |__   ___ | |_
#  | |  | | | __| | '_ ` _ \ / _` | __/ _ \   / /\ \ | '_ \| __| | '_ \ / _ \| __|
#  | |__| | | |_| | | | | | | (_| | ||  __/  / ____ \| | | | |_| | |_) | (_) | |_
#  \____/|_|\__|_|_| |_| |_|\__,_|\__\___| /_/    \_\_| |_|\__|_|_.__/ \___/ \__|

debug: false
#Antibotmode has the utility of mitigating the attack, blacklisting + ip possible,
#I tried to make it as secure as possible so as to blacklist only malicious connections
#
#At the end of the attack the blacklist is cleared for safety
#in the future I will try to make the checks as safe as possible
antibotmode:
  #Duration of the anti-botmode when activated
  keep: 15
  #If there are 5 connections in 1 second the antibot mode will be activated!
  trigger: 5

#safemode, on the other hand, has the task of making access possible
#through the timer check

safemode:
  #When 95% of the IPs have been blacklisted, safemode is activated
  percent: 95
  #Checks Per Second for enable while antibotmode is online
  modifier: 100
  #duration of safemode when activated
  keep: 20

#Pingmode allows player connections to your server!
pingmode:
  #Duration of the ping-mode when activated
  keep: 10
  #How many pings in 1 second does it take to activate the protection?
  trigger: 100
  #MotdKiller Protection
  #Send the server logo during a ping attack?
  send_info: false

#Works Only on Bungeecord Waterfall ect...
handshakemode:
  #Duration of handshakemode
  keep: 10
  #How many handshake in 1 second to enable?
  trigger: 150 #Set (Your online players * 4) | If you have 40 average online players you have to do 40 x 3 and the result will be the value to write
  #if the handshake has an invalid protocol do I have to blacklist it?
  blacklist_protocol: true
  #Enable this mode?
  enabled: true

#Minimum online time to be whitelisted
playtime_for_whitelist: 2 #minutes

taskmanager:
  analyzer: 5 #seconds
  clearcache: 5 #minutes
  queue: 1 #minutes

#This is the section where you can change the check settings
#How does it work?
#
#There is an analyzer, The analyzer is reset every 5 seconds during
#anti-botmode or safe mode, If an ip reaches the maximum number of values
#before resetting the analyzer, It is blacklisted
#
#Don't touch anything if you don't know what you are doing!
blacklist:
  #This is the section where you can change the
  #maximum number to get the blacklist for an IP
  max: 50
  #If during the safe mode a bot enters and disconnects immediately adds 20
  bypass: 20
  #If the antibot mode is online every time the bot tries to connect it adds 15
  antibot_mode: 15
  #How much the queue clears up if the antibotmode is online adds 15
  queue: 15
  #on ping during antibotmode
  ping: 3
  #if percent < 50% add 5 on connection
  usain: 5
  #Increaser Only used with ping attacks!
  ping_mode: 5
  #strange situation
  strange: 10

checks:
  #first join check
  first_join:
    enabled: true
  #slowmode check
  slowmode:
    #When a user logs in for the first time and is logged
    #out and does not come back in 15 seconds he will be
    #blacklisted for 2 to 6 minutes
    duration: 15 #seconds
    #Do I have to disconnect players within 30 seconds
    #of entering the server when it is attacked?
    disconnect: true
    #Maximum accounts for each ip
    #connected at same time
    limit: 4
    #If a player is kicked out for having too many online accounts,
    #do I have to blacklist him?
    blacklist_on_limit: true
    #Enabble this check?
    enable: true
  timer:
    #The timer check is an advanced check,
    #from a long disconnect screen a message
    #eg: "reconnect in 5 seconds"
    #if the player reconnects in those 5 seconds
    #he is whitelisted
    #here you can set minium time
    min: 5 #seconds
    #here you can set max time
    max: 10 #seconds
    #When the time for verification runs out,
    #you have 1 second to enter
    between: 1000 #milliseconds (1 SECOND)
    #If you reconnect earlier (in the case of
    #a standard configuration) after 2 failed
    #checks it will be blacklisted
    increaser: 25
    #There must be exactly 3 correct
    #checks to be whitelisted
    repeat: 3
    #If you don't enable it
    #you are a really bad person :c
    enable: true
filter: #works on Waterfall Spigot & PaperSpigot no on BungeeCord
  - 'InitialHandler has'
  - 'Connection reset by peer'
  - 'Unexpected packet received'
  - 'read timed out'
  - 'to process!'
  - 'Empty Packet!'
  - 'corrupted'
  - 'bad packet ID'
  - 'InitialHandler - encountered exception'
  - 'com.mojang.authlib'
  - 'lost connection: Timed out'
  - 'lost connection: Disconnected'
  - 'Took too long to log in'
  - 'Another plugin has cancelled the connection for' # for luckyperms on spigot
  - 'disconnected with' #for slowjoincheck`

##Meassages

`version: 2.5
args_error: '&cUse /uab help'
reload: '&aReload Completed!'
title:
  title: '&a%blocked% Blocked Bots'
  subtitle: '&6%ip%% BlackListed IP'
actionbar:
  no-attack: '&6Join &e$1 &b- &6Ping &e$2 &b- &6Queue &e$3 - &6Whitelist &e$4 &b- &6Check &e$5 » &c&l%type%'
  safe_mode: '&6Bot &e$1/sec &b- &6Ping &e$2/sec &b- &6Queue &e$3 &b- &6Blacklist &e$4 &b- &6Check &e$5 » &6&l%type%'
  antibot_mode: '&6Bot &e$1/sec &b- &6Ping &e$2/sec &b- &6Queue &e$3 &b- &6Blacklist &e$4 &b- &6Check &e$5 » &a&l%type%'
  handshake: '&6HandShakes &e$1/sec &b- &6Queue &e$2 &b- &6Blacklist &e$3 &b- &6Check &e$4 » &a&l%type%'
console:
  on_attack: '&6Bot &e$1/sec &b- &6Ping &e$2/sec &b- &6Queue &e$3 &b- &6Blacklist &e$4 &b- &6Check &e$5 » &6&l%type%'
  handshake: '&6HandShakes &e$1/sec &b- &6Queue &e$2 &b- &6Blacklist &e$3 &b- &6Check &e$4 » &a&l%type%'
help:
  - '&4/uab &chelp'
  - '&4/uab &ctoggle &factionbar/title'
  - '&4/uab &creload'
  - '&4/uab &cstats'
  - '&4/uab &cantibotmode &fon/off'
  - '&4/uab &cclearwhitelist'
  - '&4/uab &cclearblacklist'
  - '&4/uab &caddblacklist &f<ip>'
  - '&4/uab &cremoveblacklist &f<ip>'
  - '&4/uab &caddwhitelist &f<ip>'
  - '&4/uab &cremovewhitelist &f<ip>'
stats:
  - '&4Current &cBot &f$1'
  - '&4Current &cPing &f$2'
  - '&4Current &cQueue &f$3'
  - '&4Checking &cList &f$4'
  - '&4Current &CWhitelist &f$6'
  - '&4Current &cBlacklist &f$7'
  - '&4Bot &cBlocked &f$8'
  - '&4Total &cPing &f$9'
antibotmode:
  - '&4Ultimate&cAnti&fBot'
  - '&7We are receiving a bot attack!'
  - '&7--------------------------------'
  - ''
  - '&cThe AntibotMode is currently Online!'
  - '&cIt will remain active until &f$1%&c of IPs are blacklisted'
  - '&cDon''t connect too many times or you will be blacklisted!'
  - '&cBlacklist status &f$2%'
  - ''
  - '&7______________________________'
  - '&emc.yourserver.net'
first_join:
  - '&4Ultimate&cAnti&fBot'
  - '&7--------------------------------'
  - ''
  - '&cWe are analyzing your connection!'
  - '&cNow you can re-join'
  - ''
  - '&7--------------------------------'
  - '&emc.yourserver.net'
safe_mode:
  - '&4Ultimate&cAnti&fBot'
  - '&7We were unable to verify you in time!'
  - '&7--------------------------------'
  - ''
  - '&cThe server has received a bot attack and you have been disconnected'
  - '&cRe-enter the server in exactly in $1 seconds'
  - '&cIf you are wrong you will have to do it all over again'
  - '&cRemaining&f $2'
  - '&7--------------------------------'
  - '&7If the counter stays still for too long it waits 20 seconds'
  - '&emc.yourserver.net'
account-online:
  - '&4Ultimate&cAnti&fBot'
  - '&7--------------------------------'
  - ''
  - '&cYou have too many accounts connected at the same time on the server!'
  - ''
  - '&7--------------------------------'
  - '&emc.yourserver.net'
blacklisted:
  - '&4Ultimate&cAnti&fBot'
  - '&7--------------------------------'
  - ''
  - '&cYou have been blacklisted by the Antibot System'
  - '&cWhen the attack ends you will be able to join'
  - '&cEstimated time: &f$1'
  - ''
  - '&7--------------------------------'
  - '&emc.yourserver.net'
stuff:
  less: 'less than'
  plus: 'more than'`

**Comment by Aadi-mone** [comment]
Nope, I am not getting attacked, and I can't upload .yml files in Github, because it doesn't suppot that type of file.
I may paste everything.

Config: https://mclo.gs/r1h9jLA
Msgs: https://mclo.gs/drla0mo

**Comment by Kr1S-D** [comment]
Maybe your server was lagging

**Comment by Aadi-mone** [comment]
@Kr1S-D 
It was solved, after a restart I think the VPN blocker feature might blocked it. 
thanks for the quick support.
