### ISSUE TITLE
uh

### ISSUE THREAD

**Issue by Aadi-mone** [Kr1S-D/UltimateAntibot#3]
![225](https://user-images.githubusercontent.com/87631878/135743490-d134a0c5-5544-4817-abd2-528063f882a2.PNG)
Players are not able to connect after a bot attack, I tried in my other server also after the bot attack also players cannot connect so what shd I do?

**Comment by Kr1S-D** [comment]
Please try the 3.1 version

**Comment by Aadi-mone** [comment]
oh thanks :)

**Comment by Aadi-mone** [comment]
Hello, we can't use the updated version!!!
here is the log: https://mclo.gs/8wHSC8V
please make a solution!!!!!

**Comment by Kr1S-D** [comment]
Some in your config is null
