### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Aadi-mone** [Kr1S-D/UltimateAntibot#7]
Please add something like this or something which makes that the player is not a bot and he/she can join when there is a bot attack going on.
https://docs.cyberdevelopment.es/setups/custom-captcha-site

**Comment by Kr1S-D** [comment]
This requires my own private site which I cannot have as it requires a monthly fee

**Comment by Aadi-mone** [comment]
i think there are many free hosting, and thus you can get a free domain from freedom

**Comment by Kr1S-D** [comment]
Free hosting is not efficient and could lead to disruptions in the system

~Greetings

**Comment by Aadi-mone** [comment]
Thanks
